"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username @ $hostname % $shell$shlvl : $directory\
( $git_branch)( $docker_context)( \\[$time\\])
\\$ \
"""

add_newline = false

[username]
show_always = true
style_user = "fg:cyan"
style_root = "bold fg:yellow"
format = '[$user]($style)'
disabled = false

[shell]
bash_indicator = "bash"
powershell_indicator = "pwsh"
zsh_indicator = "zsh"
cmd_indicator = "cmd"
unknown_indicator = "?sh"
format = "$indicator"
disabled = false

[shlvl]
disabled = false
format = "( [#$shlvl]())"

[hostname]
ssh_only = false
format = '[$hostname](bold green)( via ssh[$ssh_symbol](bold blue))'
disabled = false

[directory]
style = "fg:bold cyan"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[time]
disabled = false
time_format = "%T"
format = '$time'
