#!/usr/bin/perl
# IBeam cursor in urxvt
# from https://github.com/okitavera/dotfiles/blob/97587f9770746e0f8a6c13b70846f084d7e200d0/home--gui/.urxvt/ext/ibeamcursor

use strict;
use warnings;

sub on_start
{
    my ($self) = @_;
    my $cmd = "\033[5 q\r";
    $self->cmd_parse ($cmd);
}
